# Generated by Django 6.0 on 2025-12-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('anons', models.CharField(verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
            ],
        ),
    ]
